// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SALVADOR_SUPER_CLAS.Data;

#nullable disable

namespace SALVADOR_SUPER_CLAS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915165237_InicialDB")]
    partial class InicialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.Property<int>("ID_Asiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Asiento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ID_Salida")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ID_Asiento");

                    b.HasIndex("ID_Salida");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Pasajero", b =>
                {
                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre_Completo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Documento");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.Property<int>("ID_Salida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Salida"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa_Vehiculo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Salida");

                    b.HasIndex("Placa_Vehiculo");

                    b.ToTable("Salidas");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Vehiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.HasKey("Placa");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Venta", b =>
                {
                    b.Property<int>("ID_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Venta"));

                    b.Property<string>("Documento_Pasajero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Fecha_Transaccion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Asiento")
                        .HasColumnType("int");

                    b.Property<string>("Metodo_Pago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Token_Boletero")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_Venta");

                    b.HasIndex("Documento_Pasajero");

                    b.HasIndex("ID_Asiento")
                        .IsUnique();

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Salida", "Salida")
                        .WithMany("Asientos")
                        .HasForeignKey("ID_Salida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Vehiculo", "Vehiculo")
                        .WithMany("Salidas")
                        .HasForeignKey("Placa_Vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Venta", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Pasajero", "Pasajero")
                        .WithMany("Ventas")
                        .HasForeignKey("Documento_Pasajero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Asiento", "Asiento")
                        .WithOne("Venta")
                        .HasForeignKey("SALVADOR_SUPER_CLAS.Models.Venta", "ID_Asiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Pasajero", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Vehiculo", b =>
                {
                    b.Navigation("Salidas");
                });
#pragma warning restore 612, 618
        }
    }
}
