// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SALVADOR_SUPER_CLAS.Data;

#nullable disable

namespace SALVADOR_SUPER_CLAS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260915224839_HU02_ValidacionesMigratorias")]
    partial class HU02_ValidacionesMigratorias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.Property<int>("ID_Asiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Asiento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ID_Salida")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ID_Asiento");

                    b.HasIndex("ID_Salida");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            ID_Asiento = 1,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 1
                        },
                        new
                        {
                            ID_Asiento = 2,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 2
                        },
                        new
                        {
                            ID_Asiento = 3,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 3
                        },
                        new
                        {
                            ID_Asiento = 4,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 4
                        },
                        new
                        {
                            ID_Asiento = 5,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 5
                        },
                        new
                        {
                            ID_Asiento = 6,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 6
                        },
                        new
                        {
                            ID_Asiento = 7,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 7
                        },
                        new
                        {
                            ID_Asiento = 8,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 8
                        },
                        new
                        {
                            ID_Asiento = 9,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 9
                        },
                        new
                        {
                            ID_Asiento = 10,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 10
                        },
                        new
                        {
                            ID_Asiento = 11,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 11
                        },
                        new
                        {
                            ID_Asiento = 12,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 12
                        },
                        new
                        {
                            ID_Asiento = 13,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 13
                        },
                        new
                        {
                            ID_Asiento = 14,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 14
                        },
                        new
                        {
                            ID_Asiento = 15,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 15
                        },
                        new
                        {
                            ID_Asiento = 16,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 16
                        },
                        new
                        {
                            ID_Asiento = 17,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 17
                        },
                        new
                        {
                            ID_Asiento = 18,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 18
                        },
                        new
                        {
                            ID_Asiento = 19,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 19
                        },
                        new
                        {
                            ID_Asiento = 20,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 20
                        },
                        new
                        {
                            ID_Asiento = 21,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 21
                        },
                        new
                        {
                            ID_Asiento = 22,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 22
                        },
                        new
                        {
                            ID_Asiento = 23,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 23
                        },
                        new
                        {
                            ID_Asiento = 24,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 24
                        },
                        new
                        {
                            ID_Asiento = 25,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 25
                        },
                        new
                        {
                            ID_Asiento = 26,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 26
                        },
                        new
                        {
                            ID_Asiento = 27,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 27
                        },
                        new
                        {
                            ID_Asiento = 28,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 28
                        },
                        new
                        {
                            ID_Asiento = 29,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 29
                        },
                        new
                        {
                            ID_Asiento = 30,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 30
                        },
                        new
                        {
                            ID_Asiento = 31,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 31
                        },
                        new
                        {
                            ID_Asiento = 32,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 32
                        },
                        new
                        {
                            ID_Asiento = 33,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 33
                        },
                        new
                        {
                            ID_Asiento = 34,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 34
                        },
                        new
                        {
                            ID_Asiento = 35,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 35
                        },
                        new
                        {
                            ID_Asiento = 36,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 36
                        },
                        new
                        {
                            ID_Asiento = 37,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 37
                        },
                        new
                        {
                            ID_Asiento = 38,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 38
                        },
                        new
                        {
                            ID_Asiento = 39,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 39
                        },
                        new
                        {
                            ID_Asiento = 40,
                            Estado = "Libre",
                            ID_Salida = 1,
                            Numero = 40
                        });
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Pasajero", b =>
                {
                    b.Property<string>("Documento")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre_Completo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Documento");

                    b.ToTable("Pasajeros");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.Property<int>("ID_Salida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Salida"));

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Placa_Vehiculo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID_Salida");

                    b.HasIndex("Placa_Vehiculo");

                    b.ToTable("Salidas");

                    b.HasData(
                        new
                        {
                            ID_Salida = 1,
                            Destino = "Santa Cruz",
                            Fecha = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Hora = new TimeSpan(0, 20, 0, 0, 0),
                            Origen = "Cochabamba",
                            Placa_Vehiculo = "CBA-2026",
                            Tarifa = 150.00m
                        });
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Vehiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.HasKey("Placa");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Placa = "CBA-2026",
                            Capacidad = 40
                        });
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Venta", b =>
                {
                    b.Property<int>("ID_Venta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID_Venta"));

                    b.Property<string>("Documento_Pasajero")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("Fecha_Transaccion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ID_Asiento")
                        .HasColumnType("int");

                    b.Property<string>("Metodo_Pago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Token_Boletero")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID_Venta");

                    b.HasIndex("Documento_Pasajero");

                    b.HasIndex("ID_Asiento")
                        .IsUnique();

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Salida", "Salida")
                        .WithMany("Asientos")
                        .HasForeignKey("ID_Salida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salida");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Vehiculo", "Vehiculo")
                        .WithMany("Salidas")
                        .HasForeignKey("Placa_Vehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Venta", b =>
                {
                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Pasajero", "Pasajero")
                        .WithMany("Ventas")
                        .HasForeignKey("Documento_Pasajero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SALVADOR_SUPER_CLAS.Models.Asiento", "Asiento")
                        .WithOne("Venta")
                        .HasForeignKey("SALVADOR_SUPER_CLAS.Models.Venta", "ID_Asiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Pasajero");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Asiento", b =>
                {
                    b.Navigation("Venta");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Pasajero", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Salida", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("SALVADOR_SUPER_CLAS.Models.Vehiculo", b =>
                {
                    b.Navigation("Salidas");
                });
#pragma warning restore 612, 618
        }
    }
}
